### ISSUE TITLE
Running with Docker with default configurations. 

### ISSUE THREAD

**Issue by neliousness** [jveverka/file-server#4]
Just a little suggestion for noobs.. when running the appliction on docker with the default configuration , it may be important to to mention that the application should be run with the **-v** flag and that the path must match the **home** property under fileserver in the default configuration file . 

_i.e -v '/home/john/fs':/home/john/fs_

```
application.yml
fileserver:
   home :  /home/john/fs
```

**Comment by jveverka** [comment]
README updated. closing
